# Generated by Django 3.1 on 2021-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0020_auto_20210510_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('b', 'برگشت داده شده'), ('p', 'منتشر شده'), ('d', 'پیش نویس'), ('i', 'در حال بررسی')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
