# Generated by Django 3.1 on 2021-05-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0027_auto_20210511_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('b', 'برگشت داده شده'), ('d', 'پیش نویس'), ('i', 'در حال بررسی')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
