# Generated by Django 3.1 on 2021-05-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0031_auto_20210511_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('i', 'در حال بررسی'), ('d', 'پیش نویس'), ('p', 'منتشر شده'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
