# Generated by Django 3.1 on 2021-05-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0032_auto_20210512_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='articles', to='first_app.Category', verbose_name='دستهyy بندی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('i', 'در حال بررسی'), ('d', 'پیش نویس'), ('b', 'برگشت داده شده'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
