# Generated by Django 3.1 on 2021-06-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0043_auto_20210614_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('d', 'پیش نویس'), ('b', 'برگشت داده شده'), ('i', 'در حال بررسی')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
