# Generated by Django 3.1 on 2021-10-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0045_auto_20210831_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
