# Generated by Django 3.1 on 2021-10-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0047_auto_20211005_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('p', 'منتشر شده'), ('b', 'برگشت داده شده'), ('i', 'در حال بررسی')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
