# Generated by Django 3.1 on 2021-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0051_auto_20211005_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('i', 'در حال بررسی'), ('d', 'پیش نویس'), ('b', 'برگشت داده شده'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
