# Generated by Django 3.1 on 2021-10-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0052_auto_20211005_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('d', 'پیش نویس'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
