# Generated by Django 3.1 on 2021-10-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0055_auto_20211006_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('d', 'پیش نویس'), ('b', 'برگشت داده شده'), ('i', 'در حال بررسی'), ('p', 'منتشر شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
