# Generated by Django 3.1 on 2021-10-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0059_auto_20211007_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('i', 'در حال بررسی'), ('p', 'منتشر شده'), ('d', 'پیش نویس'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
